
using System;

namespace patientBackend1.Models
{
    public class MedicalReport
    {
        public string Id { get; set; } // Unique ID generated by the system
        public string Findings { get; set; } // The findings made by the doctor
        public string Diagnosis { get; set; } // The diagnosis tried by the doctor
        public string TreatmentGiven { get; set; } // The treatment given by the doctor
        public string InvestigationResults { get; set; } // The results observed by the doctor
        public DateTime Date { get; set; } // Creation date and time of the report

        // Additional properties or methods can be added here
    }
}